apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: restful-web-services-deployment
  namespace: XX_NAMESPACE_XX
spec:
  selector:
    matchLabels:
      app: restful-web-services
  replicas: 2 
  template: # create pods using pod definition in this template
    metadata:
      namespace: XX_NAMESPACE_XX
      labels:
        app: restful-web-services
    spec:
      containers:
      - name: restful-web-services
        image: group1registry.azurecr.io/services/restful-web-services:XX_IMAGETAG_XX
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name:  acr-secret
